### ISSUE TITLE
Adventure Points

### ISSUE THREAD

**Issue by PandaManII** [CutFlame/MCDSaveEdit#105]
Would it be possible to edit your adventure points?
If so, please add this feature

**Comment by ExE-Boss** [comment]
I don’t believe so, as those seem to be stored on **Microsoft**’s servers[^1] and are tied to your **Minecraft** account, which is tied to your **Microsoft** account, which is also used to facilitate cloud saves.

[^1]: This is based on the fact that you can only level your adventure rank while connected to **Microsoft**’s servers.

**Comment by PandaManII** [comment]
ok thank you!

**Comment by oniklo** [comment]
So i cant gild or enchant anything I can change my level give myself emeralds and gold and stuff but my file just isnt loading i dont know how to explain it but the enchantments are just greyed out and i simply cant click on gild so idk i need help w this and a explanation .

**Comment by CutFlame** [comment]
> Would it be possible to edit your adventure points?

Adventure Points are not found in the save file and so therefore MCDSaveEdit cannot modify them. Sorry.

> So i cant gild or enchant anything I can change my level give myself emeralds and gold and stuff but my file just isnt loading

Check the README: https://github.com/CutFlame/MCDSaveEdit#fix-missing-images
