### ISSUE TITLE
No icons showing up, not working

### ISSUE THREAD

**Issue by GoldenmageGitHub** [CutFlame/MCDSaveEdit#106]
No gear textures showing up, so I can't select enchants, gear type or gear stats
![Minecraft Dungeons Save File Editor - 51785AC94C827EE328420C9186BE4358 dat 2022 01 29  20_28_57](https://user-images.githubusercontent.com/98664462/151674859-33b6ee82-116c-4ce9-967e-371bf2654c43.png)

**Comment by Victorlef** [comment]
same here

**Comment by CutFlame** [comment]
https://github.com/CutFlame/MCDSaveEdit#fix-missing-images
