### ISSUE TITLE
how to create the executable?

### ISSUE THREAD

**Issue by tchia04** [CutFlame/MCDSaveEdit#11]
Hi, Do you have instruction on how to make executable file from this project? 

Thank you

**Comment by CutFlame** [comment]
Ah, I should put something in the readme... give me some time to throw that together. I've just been compiling with Visual Studio 2019 using the release configuration. I've kept one file out of the repo that contains the Secrets class. So you will have to acquire the AES key that unlocks the games' .pak files to fill that in.

**Comment by CutFlame** [comment]
Readme has been updated to include compile instructions.
