### ISSUE TITLE
i cant dycript pak files

### ISSUE THREAD

**Issue by str1kecodes** [CutFlame/MCDSaveEdit#110]
![image](https://user-images.githubusercontent.com/93689538/153357696-b238e736-d9bd-4754-8540-9b86bd1453aa.png)
how do i fix this

**Comment by DarwinUang** [comment]
> how do i fix this

You don't.

**Comment by xalti9** [comment]
Rn its not compatible with minecraft dungeons so you just have to wait until an update.

**Comment by CutFlame** [comment]
Sorry for the delay everyone. It seems someone published on my behalf.
