### ISSUE TITLE
Could not decrypt pak file

### ISSUE THREAD

**Issue by TerrenceXW** [CutFlame/MCDSaveEdit#113]
How can i fix it?  1.13 does not work
![image](https://user-images.githubusercontent.com/10952441/154265646-ff10e738-281f-4b5d-9697-f2906b08261a.png)

**Comment by Lonewolf1893** [comment]
Same Problem
The Editor needs an Update for the Version 1.13

**Comment by TreeBranches** [comment]
Yep, waiting for update. Seems like the encryption has changed.

**Comment by Leahexe** [comment]
Same issue, just gotta wait I guess

**Comment by LonelySauce** [comment]
Why do the Dungeons Devs even change the encryption for the game's pak files anyway? It doesn't make any sense as far as I know.

**Comment by Auirsblade** [comment]
Oof I fixed it locally but the repo ignores the Secrets.cs file so i can't push the fix for you guys.

**Comment by TreeBranches** [comment]
> Oof I fixed it locally but the repo ignores the Secrets.cs file so i can't push the fix for you guys.

You can make the file manually using GitHub's web editor.

**Comment by LonelySauce** [comment]
> > Oof I fixed it locally but the repo ignores the Secrets.cs file so i can't push the fix for you guys.
> 
> You can make the file manually using GitHub's web editor and pasting the contents, else upload the file here as an attachment to your comment, with instructions.

@Auirsblade Please do this, I don't know how to even edit a ".cs" file let alone find it and I can't be bothered to fix this myself if someone else has already done it and could just upload it.

**Comment by Auirsblade** [comment]
[Secrets.zip](https://github.com/CutFlame/MCDSaveEdit/files/8227722/Secrets.zip)

There's the file, you'll just need to follow the "Compiling" directions in the ReadMe and use that as your secrets file.

**Comment by TreeBranches** [comment]
> [Secrets.zip](https://github.com/CutFlame/MCDSaveEdit/files/8227722/Secrets.zip)
> 
> There's the file, you'll just need to follow the "Compiling" directions in the ReadMe and use that as your secrets file.

Unfortunately, instructions for compiling MCDSaveEdit yourself aren't clear and I'm getting a lot of errors. I crash coursed my way through but ultimately was unable to clone.

git clone <mcdedit_link> --recurse-submodules gives me permission errors when trying to access the submodule repositories, so I clone them manually into the respective .\MCDSaveEdit\DungeonTools and .\MCDSaveEdit\PakReader folders.

I assume I then place your Secrets.cs file into .\MCDSaveEdit\Data\ folder as noted in the Readme.

Then when loading MCDSaveEdit's .sln file and trying to compile, I get a tonne of missing file errors, and missing "referenced components"

![Untitled](https://user-images.githubusercontent.com/8653544/158016525-dd7dd490-732d-413c-8271-4c2554cb22fb.png)

**Comment by Auirsblade** [comment]
@TreeBranches yea I'm guessing you are missing a using or a reference causing that first error in the AesEncryptionProvider. Can't really guide you step by step but if you solve that the rest of the not found errors will go away.

**Comment by KeyGolemMCD** [comment]
it happens to me too.........

**Comment by Auirsblade** [comment]
You could try downloading the code from my fork. It compiled fine as of a few days ago.

**Comment by ACKREIK** [comment]
i will build it for yall

**Comment by ACKREIK** [comment]
> Ideally there'd be something in MCDEdit for us to manually load a Secrets.cs file or otherwise provide an AESKey in-app to decrypt the PAK files, to save having to recompile everytime Mojang changes the key.

i will try and do that for my version
no garuntees it will work

**Comment by ACKREIK** [comment]
> You could try downloading the code from my fork. It compiled fine as of a few days ago.

why not upload the compiled stuff then?

**Comment by ACKREIK** [comment]
building all the deps is a ton of work

**Comment by ACKREIK** [comment]
if yall want a working version dm me 
Kylee#8666
i give you the file fully compiled

**Comment by CutFlame** [comment]
Sorry for the delay everyone. It seems someone decided to publish on my behalf.
