### ISSUE TITLE
[FIXED PKG AND PAK ERRORS] I really hate people who are delaying giving out their free version even though the paid (which becomes release) gets fully released

### ISSUE THREAD

**Issue by GamingManPro** [CutFlame/MCDSaveEdit#115]
~~I really hate people who are delaying giving out their free version even though the paid (which becomes release) gets fully released~~
im just a bitch
if you want to discord Cheesi#4440

**Comment by LonelySauce** [comment]
I agree with this sentiment. It's one thing for it to be for a beta where there are numerous bugs to fix but this was literally just changing the decryption key to one that works. Now I don't have to wait over a month for me to be able to get the full release!

**Comment by CutFlame** [comment]
Message me on Discord please.
