### ISSUE TITLE
Save File not in expected format

### ISSUE THREAD

**Issue by NKQ123** [CutFlame/MCDSaveEdit#117]
I converted the save file from switch to pc, it says Save File not in expected format then when I re-save on my pc, then it can be opened
[174C722108D837056BEFF8DAB77F5487.txt](https://github.com/CutFlame/MCDSaveEdit/files/8367917/174C722108D837056BEFF8DAB77F5487.txt)
(convert this txt to dat).

**Comment by CutFlame** [comment]
Well, that's interesting. The good news is I was able to write some code that would decrypt it. Bad news is, I will need to add that code to MCDSaveEdit in order to support these types of files.

**Comment by NKQ123** [comment]
Oh I see, is it complicated?

**Comment by ACKREIK** [comment]
The save file should be saved as just a plain file, why was it a txt file?
also you need to convert it to .dat via an external tool, then load it via pc mc dungeons, then open the .dat
then convert it back to plain text

**Comment by ACKREIK** [comment]
https://youtu.be/rax87LrfFOY
this is how i did it, it works for me

**Comment by NKQ123** [comment]
> The save file should be saved as just a plain file, why was it a txt file? also you need to convert it to .dat via an external tool, then load it via pc mc dungeons, then open the .dat then convert it back to plain text the tool needed is actually in mcd save edit, but i dont think its accessible https://github.com/HellPie/DungeonTools this is the tool.

Yes, I did it exactly like this. Its a txt file because github don't support on uploading plain file, so I converted it to a txt file. I can edit the save file by the steps. I think the step "load in pc Mc dungeons" is a bit annoying than just convert it to pc format.

**Comment by Alexexexex** [comment]
figured out what is the problem, after update 1.12 of the switch version of the game the save files are totally a mess, you just need to erase the part of your save file after the first and reeeeeealy long string, everything after that is just gliched code that is repeated and not used, dont know the reason though why that part exist and why isnt erased automatically when dumping the save files. I will attach my save file before and after as reference:
[Character1776552308D801C4B888156B97F6D91D(before).txt](https://github.com/CutFlame/MCDSaveEdit/files/8502746/Character1776552308D801C4B888156B97F6D91D.before.txt)
[Character1776552308D801C4B888156B97F6D91D(after).txt](https://github.com/CutFlame/MCDSaveEdit/files/8502747/Character1776552308D801C4B888156B97F6D91D.after.txt)

.

**Comment by CutFlame** [comment]
I have attempted to solve the issues with reading the console savefiles in version MCDSaveEdit 1.5.3.0.
Does it work? Can I close this issue?

**Comment by NKQ123** [comment]
hi sorry for the late reply, don't know whether is my problem or not, whenever i open a save file it shows not respoinding and the program closed. Probably my mc dungeons havent been updated to the

**Comment by NKQ123** [comment]
I will send two txt file to you here, the first one is encrypted (change the file extension to dat) whereas the second one is decrypted (change the file extension to json) would you kindly help me to test? Thanks
[Character174C722108D837056BEFF8DAB77F5487.txt](https://github.com/CutFlame/MCDSaveEdit/files/8567885/Character174C722108D837056BEFF8DAB77F5487.txt)
[Character174C722108D837056BEFF8DAB77F5487 (2).txt](https://github.com/CutFlame/MCDSaveEdit/files/8567895/Character174C722108D837056BEFF8DAB77F5487.2.txt)

**Comment by ACKREIK** [comment]
> I have attempted to solve the issues with reading the console savefiles in version MCDSaveEdit 1.5.3.0. Does it work? Can I close this issue?

Seems to work.

**Comment by NKQ123** [comment]
it worked, thanks for your hard work 🤗🤗🤗
