### ISSUE TITLE
Fails to save

### ISSUE THREAD

**Issue by Lunarfire344** [CutFlame/MCDSaveEdit#118]
Whenever I try to save the modified file the editor just crashes. Changes are not applied.

**Comment by Lunarfire344** [comment]
Just noticed that the save files are DAT not PAK. Could that be causing the problem?

**Comment by CutFlame** [comment]
The save files are usually named a string of 32 letters and numbers and then end with ".dat". Like here is the name of one of my files: `5A9FB36A4984F2262AC7CBB0B5117EBE.dat`. If you continue to have problems please send me your save file and I will debug it.

**Comment by Lunarfire344** [comment]
It looks like It was a problem with the save files. I tried saving it as a new file and it worked.
