### ISSUE TITLE
Armor Attributes not Enchantments Potion Use Boosts Defense (Potion Barrier) such as that would be on Stalwart Armor

### ISSUE THREAD

**Issue by Kithkani** [CutFlame/MCDSaveEdit#13]
Great work in 1.2.5, stoked you added armor editing. The only potion option I saw was Cooldown Decrease. If it's not a terrible bother please add this on one of your future commits. Thank you so much for all your hard and awesome work on this project.

**Comment by CutFlame** [comment]
The unique armor properties or enchantments on unique armors can't be changed (like the "Potion Use Boosts Defense" on the Stalwart Armor). That information is not set in the save files. Sorry, nothing I can do for that.
