### ISSUE TITLE
No files found

### ISSUE THREAD

**Issue by GlytchedMatrix** [CutFlame/MCDSaveEdit#133]
I downloaded and everyone works until I open it and its cant find my .paks. so I god to microsoft/apps/dungeons/products/paks and nothing there. I downloaded from the xbox app but this save file editor cant find my gamefiles. I'm on windows 11 if that helps

**Comment by LuckyPants12** [comment]
You shoukd have a path to XboxGames folder , go to the drive you installed xbox on , normally the C drive, and you will see a XboxGames folder there, open it and you should see your installation, open the folder and go to `Dungeons\Content\Paks`
you will see your pack files there

**Comment by GlytchedMatrix** [comment]
> You shoukd have a path to XboxGames folder , go to the drive you installed xbox on , normally the C drive, and you will see a XboxGames folder there, open it and you should see your installation, open the folder and go to `Dungeons\Content\Paks` you will see your pack files there

It's okay I found out apperently 1.5.2.0 apperently just didn't like me but 1.5.3.0 worked just fine
