### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Evoal** [CutFlame/MCDSaveEdit#134]
the app crashes when I try to load my character file.

Here's the SaveFile:
[FE44DC5E4DF893F262CDF3A0FD249DD5.zip](https://github.com/CutFlame/MCDSaveEdit/files/8636627/FE44DC5E4DF893F262CDF3A0FD249DD5.zip)

**Comment by Swireqs** [comment]
same i cant load my savefile

**Comment by CutFlame** [comment]
Latest version has now been published here on github. https://github.com/CutFlame/MCDSaveEdit/releases
I was able to load your file with the latest version of MCDSaveEdit
