### ISSUE TITLE
I can't open my game after editing a save

### ISSUE THREAD

**Issue by radio295** [CutFlame/MCDSaveEdit#136]
I edited my save, and after giving another enchant to a piece of armor I suddenly can't open my game anymore

I own the game on PC Gamepass if that helps for anything

**Comment by radio295** [comment]
![4E61AFE0-D203-42DF-9B86-7056DE714FC1](https://user-images.githubusercontent.com/105389942/167943362-8a0c0a08-1025-4cbc-b5b2-8abc9f72fd50.jpeg)

**Comment by CutFlame** [comment]
I can't promise that MCDSaveEdit keeps your character file playable. I hope you had backups. Also, that crash error doesn't seem to be related to your changes.
