### ISSUE TITLE
Minecraft Dungeons ver. 1.14.1 --> .1.15.0

### ISSUE THREAD

**Issue by rjbprime** [CutFlame/MCDSaveEdit#140]
Hi @CutFlame, just opened steam and recieved an update of Minecraft Dungeons to version 1.15.0. Using the currently available MCDSave Editor, it says on launch of the 1.5.3.0 that it failed to load game content, and that it can't decrypt the pak files at the install location. Seems that the decryption keys for the game have changed again.

Is it possible and safe(!!) to use the save editor without being able to decrypt the pak files?

**Comment by Evoal** [comment]
> 

Don't use the editor with incompatible Version wait until the author update the editor.

**Comment by TokenElite** [comment]
I have experienced this also, since the 5/25/22 patch the encryption key has changed.

**Comment by CutFlame** [comment]
@rjbprime it is possible to use the old version (just load with no content) but it will not have all the features. Also depending on the changes that MCD makes to their file structure you could lose game progress. That's the biggest thing I try to always test before releasing the next version.
