### ISSUE TITLE
5/26/22 Unable to find game files

### ISSUE THREAD

**Issue by TokenElite** [CutFlame/MCDSaveEdit#141]
Current patch released Tuesday 5/25/22 for MCD causes unable to decrypt pak files with this editor. Keep up the good work.

**Comment by AexDEye9** [comment]
i heard it's up for his patrons, but i don't know the time between early patron release and public release

**Comment by Bunkerpoo420** [comment]
So where it's his patreon? xD

**Comment by TokenElite** [comment]
I'm new to GitHub not sure how to Patron someone, but I'd be willing to throw him a few bones to access it now

**Comment by AexDEye9** [comment]
Essentially i'm just waiting for the update build to go public

**Comment by CutFlame** [comment]
Latest version has been released.
