### ISSUE TITLE
Minecraft Dungeons ver. 1.15.0 --> .1.15.1 // Thursday 9th June 2022

### ISSUE THREAD

**Issue by rjbprime** [CutFlame/MCDSaveEdit#142]
Hi @CutFlame, just opened steam and recieved an update of Minecraft Dungeons to version 1.15.1.0 today. Seems that the encyption has changed again?

**Comment by taylom22** [comment]
Yes! It definitely has. Don't want to sound impatient since I really appreciate everything the contributors have done on this project, but I am curious how long it usually takes to update.

**Comment by Koobaczech** [comment]
My friend @rjbprime . just wanted to share some insight. I was able to use the Steam Console to download the previous version of MCD (1.15.0.0), and use that downloaded assets .paks to run MCDEdit without issues. Just lookup how to downgrade a Steam game for more information. I did bother @CutFlame already about it over on Patreon and feel bad enough, so glad I was able to move forward.

**Comment by CutFlame** [comment]
Latest version has been released.
