### ISSUE TITLE
1.15.1

### ISSUE THREAD

**Issue by finleythepro** [CutFlame/MCDSaveEdit#143]
It doesn't work for 1.15.1! Please make a updated version so I can post my YT tutorial!

**Comment by finleythepro** [comment]
![Screenshot (68)](https://user-images.githubusercontent.com/80583951/173183153-63161d8d-e27b-4fa0-b87a-be8d2816e05e.png)

**Comment by Janakthegamer** [comment]
don't be impatient

**Comment by Koobaczech** [comment]
@finleythepro Same as I told the last person, there is a temporary fix. 

1. Using steam console, download the previous version of Minecraft Dungeons (1.15.0.0).
2. That download be placed in a separate folder and will not mess up your 1.15.1 game.
3. Use that downloaded versions .paks to run MCDEdit 1.5.4.0 without issues. Just lookup how to downgrade a Steam game for more information.
4. As an alternate, support Cutflame on Patreon for all his hard work. The latest MCDEdit is already out for us supporters

**Comment by CutFlame** [comment]
Latest version has been released.
