### ISSUE TITLE
no pak files EDIT: I found the files never mind

### ISSUE THREAD

**Issue by coolguy999999** [CutFlame/MCDSaveEdit#144]
I can't find the files even though I looked through WindowsApps folder, Mojang Studios folder, XboxGFames folder or anything. (I'm using the microsoft store version on windows 11). Please help me find out a way to get to the .pak files (I'm using the latest version of MCD Save Edit by the way) EDIT: I fixed the problem

**Comment by Doodlefishone** [comment]
How did you fix it? I'm having a hard time trying to fix it.

**Comment by 1RedOne** [comment]
Try this location '%userprofile%\Saved Games\Mojang Studios\Dungeons\'
