### ISSUE TITLE
MCDEdit loads but crashes 

### ISSUE THREAD

**Issue by CryptTized** [CutFlame/MCDSaveEdit#145]
So usually when I load MCDEdit, there would usually be a loading logo when opening. But It doesn't in my case anymore. It just crashes and no loading logo is displayed. It used to work before and after I turned my pc off, this is the result. 
![image](https://user-images.githubusercontent.com/107989419/174983315-187bb855-6c2d-4158-a85a-a98601eecb69.png)

**Comment by raffel080108** [comment]
Cannot confirm this using latest version. The only crash I have experienced so far, is when attempting to use the "Transfer to stroage" button

**Comment by CutFlame** [comment]
Latest version has now been published here on github. https://github.com/CutFlame/MCDSaveEdit/releases
