### ISSUE TITLE
app crasing while opening character files

### ISSUE THREAD

**Issue by tR00I** [CutFlame/MCDSaveEdit#146]

**Comment by CutFlame** [comment]
Could you please provide your character file? It would help me fix MCDSaveEdit.

**Comment by tR00I** [comment]
[FE1C25854E5BFEA56C7E08A5F1730841.zip](https://github.com/CutFlame/MCDSaveEdit/files/9438061/FE1C25854E5BFEA56C7E08A5F1730841.zip)
Here's my character file

**Comment by CutFlame** [comment]
It seems to open just fine in MCDSaveEdit 1.5.7.0. Let me know if this is still an issue.
