### ISSUE TITLE
save edit no longer works

### ISSUE THREAD

**Issue by B33LOX** [CutFlame/MCDSaveEdit#149]
my save edit doesn't work anymore when the previous versions did, it doesn't find the .pak files anymore, but when I go to File->Open it finds all my files and loads them with the limited version. I put exactly the same path but nothing happens, save edit does not find them: 'Could not find game content files at the given path'. Help pls (Im playing on Windows 10)

**Comment by raffel080108** [comment]
Cannot confirm this using the latest release. Maybe the issues was resolved in a recent update. Everything works fine, at least for me

**Comment by CutFlame** [comment]
Latest version has now been published here on github. https://github.com/CutFlame/MCDSaveEdit/releases
