### ISSUE TITLE
blank icons/ enchants

### ISSUE THREAD

**Issue by avatar7652** [CutFlame/MCDSaveEdit#15]
![image](https://user-images.githubusercontent.com/73441753/101849312-73f1fe80-3b25-11eb-9393-68db586184a2.png)
 it does that with both versions and doest let me change anything

**Comment by CutFlame** [comment]
I'm assuming, since you closed this issue yourself, you found the path to your game files for it to use and everything worked after that?

**Comment by avatar7652** [comment]
I kinda found a way too it with all the old enchants but the new ones are
bugged out for me from what I can tell

**Comment by CutFlame** [comment]
Try the latest version. It asks where to find your game content if it's not in the default install location.

**Comment by avatar7652** [comment]
I tried that but it gives me an error ill send screenshots later im
probably doing something wrong
