### ISSUE TITLE
Noticed that enchant count ends up being negative...good first issue?

### ISSUE THREAD

**Issue by 1RedOne** [CutFlame/MCDSaveEdit#151]
Hi!  I am a C# programmer and would like to fix this.  Is there a reason we save files with negative enchant points? 

# Repro Steps
* Import a new level 1 character
* Use the editor to add two points to an item
* Observe that the enchant points count will be `-2`.
* This carries over after saving into the game as well

# Proposal
* Maintain all current logic
* On saving, if count of enchant > 0, then save as 1 or 0.  

Let me know if you like this, and I'll do it.

**Comment by raffel080108** [comment]
Could not replicate this issue on latest release, all enchantments are displayed and function correctly (I created a completely new item and added 3 enchantments, for reference)

**Comment by 1RedOne** [comment]
That's the issue I was talking about, where it is possible to end up with negative enchants.  

If you have a character with no spare points, and add a level of any enchant to a piece of gear, the character's overall enchantment point count decreases to below 0.

If this is intentional to prevent a buffer underrun or some kind of error in the game, then I understand it and we can just clarify this behavior with a tool tip on the enchant point field.

But if it isn't then I think a better option is to just save it at zero points.

**Comment by CutFlame** [comment]
The enchantment points are not saved in the character save file. They are computed based on the character level minus the total number of enchantment points used on items in the player's inventory.

Code from [ProfileExtensions.cs](https://github.com/CutFlame/MCDSaveEdit/blob/daa7ef2d122744638a42f6b4d0adae5d4fe67051/MCDSaveEdit/Logic/Extensions/ProfileExtensions.cs):
```csharp
public static int remainingEnchantmentPoints(this ProfileSaveFile profile)
        {
            int totalEnchantmentPointsUsed = 1;
            foreach (var item in profile.allItems())
            {
                totalEnchantmentPointsUsed += item.enchantmentPoints();
            }
            return profile.level() - totalEnchantmentPointsUsed;
        }
```

**Comment by 1RedOne** [comment]
Thank you, that makes complete sense, not actually a bug then at all!
