### ISSUE TITLE
mcdsaveedit crashing on startup/unexpected file format

### ISSUE THREAD

**Issue by noob111111** [CutFlame/MCDSaveEdit#152]
1.1.2 works perfectly but
1. no pictures
2. old (doesn't have new additions in newer versions)

1.2.0 + 1.2.1 runs but has "unexpected file format" i tried using the .dat and the .json (using dtools)

1.2.2 + 1.2.3 doesn't even run

1.2.4 + 1.2.5 opens this in the top left corner
![image](https://user-images.githubusercontent.com/90646226/180789896-75ceb6c4-4602-424c-bd3b-d77b682f354b.png)

1.2.6 and later "runs" and crashes
![image](https://user-images.githubusercontent.com/90646226/180790088-18d1f60c-f0f2-423c-8017-bf760931b492.png)
(note 1.2.6 and later is the same issue as #145 )

(note 2 i cant get .NET Framework 4.7.1 because ".NET Framework 4.7.1 or a later update is already installed on this computer.")

**Comment by Converse05** [comment]
Can confirm with latest version 
![image](https://user-images.githubusercontent.com/110313851/182004482-d6ef5100-1548-412b-8ff8-2a4c093d45f5.png)

**Comment by CutFlame** [comment]
Latest version has now been published here on github. https://github.com/CutFlame/MCDSaveEdit/releases
If you are still seeing issues please send me a copy of your character file you are trying to open and I will take a look.
