### ISSUE TITLE
App crasing while opening character files

### ISSUE THREAD

**Issue by Landidi666** [CutFlame/MCDSaveEdit#153]
MCDSaveEdit crashes without warning when I open .dat file
Here is my .dat file
[F4D940AE49F7D25350CA5B87F33D0126.dat.zip](https://github.com/CutFlame/MCDSaveEdit/files/9250213/F4D940AE49F7D25350CA5B87F33D0126.dat.zip)
You need to delete the ".zip" at the end of the filename.

**Comment by CutFlame** [comment]
It seems to open and work just fine with MCDSaveEdit 1.5.7.0. Let me know if this is still an issue.
