### ISSUE TITLE
Suddenly won't open anymore

### ISSUE THREAD

**Issue by enderplayer2002** [CutFlame/MCDSaveEdit#156]
No idea why it stopped working, it simply won't open anymore, crashes before even loading. Do these minidump files i found help? Is there a way to, idk, "reset" the app maybe?

[MCDSaveEdit.exe.20036.zip](https://github.com/CutFlame/MCDSaveEdit/files/9571001/MCDSaveEdit.exe.20036.zip)
[MCDSaveEdit.exe.1856.zip](https://github.com/CutFlame/MCDSaveEdit/files/9571003/MCDSaveEdit.exe.1856.zip)
[MCDSaveEdit.exe.16692.zip](https://github.com/CutFlame/MCDSaveEdit/files/9571011/MCDSaveEdit.exe.16692.zip)
[MCDSaveEdit.exe.10856.zip](https://github.com/CutFlame/MCDSaveEdit/files/9571015/MCDSaveEdit.exe.10856.zip)

**Comment by WaterFlavors** [comment]
I fixed mine by deleting the 'Minecraft Dungeons' application in Add or remove programs. It only had like 16 kb so I believe it's not the base game.

**Comment by enderplayer2002** [comment]
I'm closing this issue as I've figured out the cause. I changed the game folder to my ssd because i needed more space, and instead of showing the prompt asking for the game files, the editor simply crashed.
