### ISSUE TITLE
is this abandoned?

### ISSUE THREAD

**Issue by noob111111** [CutFlame/MCDSaveEdit#157]
ok so on july 25th i opened issue #152 which gave ALOT of information, so much so, that i will say, you would have fixed it by now... IF YOU ACTUALLY CARED ABOUT THIS PROJECT!!!

ok so, the last update was a couple months ago by now, multiple people opened multiple isssues
and you didnt fix any of them

so i am guessing that's enough evidence that this project is abandoned... :/

**Comment by Delfite** [comment]
Looking at CutFlame's recent activity on github, they haven't made ANY commits since the middle of July, I think it's safe to say that the only Save Editor program is now dead. If someone could please make a fork of this project and fix the crashing issues everyone is having then that would be great.

**Comment by EnderNon** [comment]
> If someone could please make a fork of this project and fix the crashing issues everyone is having then that would be great.

we can only wish :(

in the meantime if you really want something similar, Birdi's cheat engine table can edit things while the game is running but theres likely to be lots of errors etc

**Comment by Aplixion** [comment]
@EnderNon - Do you have a link to Birdi's CE table? or any other currently working one?

**Comment by Aplixion** [comment]
See issue #162 for an update.

**Comment by EnderNon** [comment]
> See issue #162 for an update.

also, it seems you asked for a link to Birdi's cheat table. it's in their discord, and they don't give permission for you to distribute it. its only available for 1 week after the table updates or 2 weeks after the game updates, then its gone. except for donators < 10$ who can access for 6 weeks, and people who donate > 10$ get access permanently

**Comment by CutFlame** [comment]
MCDSaveEdit 1.5.7.0 is released
