### ISSUE TITLE
Proof that this project is not dead, and we may see an update in the near future!

### ISSUE THREAD

**Issue by Aplixion** [CutFlame/MCDSaveEdit#162]
CutFlame has just replied (about an hour ago) to my inquiry about this project, over on his Patreon page. We can all rejoice knowing that this project has not been abandoned! 

He's stated the following: "Sorry this next update is taking longer than usual. The devs made lots of changes."

Link to his Patreon page below ↓
https://www.patreon.com/cutflame/posts

**Comment by EnderNon** [comment]
no way! real!

**Comment by noob111111** [comment]
amazing! hope he fixes the problems i mentioned on #152

**Comment by CutFlame** [comment]
MCDSaveEdit 1.5.7.0 is released
