### ISSUE TITLE
could not decrypt pak files

### ISSUE THREAD

**Issue by ifuckdogs1337** [CutFlame/MCDSaveEdit#163]
hello, i am using the beta version on patreon (1.5.5.2)
and i am getting this error
![image](https://user-images.githubusercontent.com/100514348/197393281-240f4c3b-41d1-4db4-a67d-2977adac1bfc.png)

**Comment by JarzaClay** [comment]
I am having the same issue with the 1.5.5.0 release. I believe it is because Minecraft Dungeons recently updated.

**Comment by localblobofmeat** [comment]
same thing

**Comment by Wakotomo** [comment]
same :(

**Comment by NicolasDiSi** [comment]
its a shame ai don´t have the time to be a contributor in this proyect.
Anyways same issue, i love the tool. its Really useful to test build and enchant convinations.

**Comment by Wakotomo** [comment]
NEXUS mod has update1.5.6.0!!! can use now!

**Comment by ifuckdogs1337** [comment]
https://www.patreon.com/cutflame/
new versions here

**Comment by CutFlame** [comment]
MCDSaveEdit 1.5.7.0 is released
