### ISSUE TITLE
Error "You dont have the right license for game"

### ISSUE THREAD

**Issue by KotSusowy** [CutFlame/MCDSaveEdit#164]
When I wanna change the character and choose the game files it still says that it still cant see the game files and problay is beacuse the mcd save edit version is 1.5.5.0 and mc d version is 1.16.2.0 but is it normal that if i only change the emeralds and gold by using no game content then when the game is being opened it says that i dont have the right license for the game

**Comment by CoookieCat** [comment]
idk maybe just pay for new version https://www.patreon.com/cutflame

**Comment by CoookieCat** [comment]
or again install minecraft dungeons

**Comment by CutFlame** [comment]
MCDSaveEdit 1.5.7.0 is released
