### ISSUE TITLE
MCD save edit not working for MCD S3

### ISSUE THREAD

**Issue by lyndisMikiyoko** [CutFlame/MCDSaveEdit#165]
You cant seem to edit the enchantments on weapons anymore. Has the project been abandoned or are you working on a new update to fix the issue?

**Comment by lukss21** [comment]
yeah it's bug bcz there's a new MCD version and this program its outdated

**Comment by localblobofmeat** [comment]
i think it will be fixed after minecraft dungons stops updating for a tiny bit

**Comment by CoookieCat** [comment]
there is a new version but you have to pay for it https://www.patreon.com/cutflame

**Comment by CutFlame** [comment]
MCDSaveEdit 1.5.7.0 is released
