### ISSUE TITLE
Cannot decrypt .pak

### ISSUE THREAD

**Issue by ArchooD2** [CutFlame/MCDSaveEdit#166]
As the auto-file-finder runs, it tries to decrypt the .pak files.
It fails, and throws an error; also asking if I have the right version. This could be because the Github version is slightly behind the Nexus version; but since there was a hotfix recently, neither are working.

**Comment by ifuckdogs1337** [comment]
https://www.patreon.com/cutflame/posts
working versions here

**Comment by CutFlame** [comment]
MCDSaveEdit 1.5.7.0 is released
