### ISSUE TITLE
MCDSabeEdit failed to load game content

### ISSUE THREAD

**Issue by SpareGiraffe345** [CutFlame/MCDSaveEdit#167]
I got the latest available version of MCDSaveEdit (1.5.5.0) and  keep getting this error that says 
failed to load game content could not decrypt pak files.

I use the Minecraft launcher version of Minecraft dungeons and When I launch MCDSaveEdit and select my character file I don’t have the ability to add items or enchantments 

I can only change Number values like level, currency or power. I can't see images either. ᕕ༼✿•̀︿•́༽ᕗ

**Comment by ifuckdogs1337** [comment]
https://www.patreon.com/cutflame/
working versions here

**Comment by SpareGiraffe345** [comment]
Would I be able to do the subscription, get the files I need and then cancel the subscription

**Comment by Flubbedsoda6010** [comment]
> https://www.patreon.com/cutflame/ working versions here

why don't you update it on github?

**Comment by CutFlame** [comment]
MCDSaveEdit 1.5.7.0 is released
