### ISSUE TITLE
Please update for MCD 1.17

### ISSUE THREAD

**Issue by NotchApple1703** [CutFlame/MCDSaveEdit#169]
It said cannot decrypt pak files

**Comment by ifuckdogs1337** [comment]
https://www.patreon.com/cutflame/posts

**Comment by Pixconix** [comment]
are you required to pay money to still be able to mod?

**Comment by CutFlame** [comment]
Latest version has now been published here on github. https://github.com/CutFlame/MCDSaveEdit/releases
