### ISSUE TITLE
MCDSaveEdit crashes when i try to open

### ISSUE THREAD

**Issue by Skeppr** [CutFlame/MCDSaveEdit#170]
I have Minecraft dungeons 1.17 (pirated). The game is located in prigram files x86 and works flawlessly. When I open the program, even with admin perms, it shows searching for paks then crashes. https://i.imgur.com/p2G6aWJ.mp4 sry for bad resolution idk y it does that

**Comment by CutFlame** [comment]
Latest version has now been published here on github. https://github.com/CutFlame/MCDSaveEdit/releases
