### ISSUE TITLE
Beehive and Wither Armor: Special Abilities missing 

### ISSUE THREAD

**Issue by BDokey** [CutFlame/MCDSaveEdit#18]
HI I encounter an issue with certain armors: Beehive and Wither Armor.

Problem: The Special Abilities do not apply/overwrite when being replaced from the previous armor. (The previous armor abilities are still active)

I have attached a few images. 
I'm not sure what's causing the issue since I can overwrite other unique armors; like the Halloween items with no issues.

I am doing something wrong or is this a bug?

Thanks

![Screenshot 2021-01-02 012050](https://user-images.githubusercontent.com/76866055/103454546-28e98800-4c9a-11eb-92f7-6c9929640d02.png)
![Screenshot 2021-01-02 012149](https://user-images.githubusercontent.com/76866055/103454549-2b4be200-4c9a-11eb-8c4f-d7ecb05758a5.png)

**Comment by BDokey** [comment]
My bad. I didn't notice I have to change the armor properties as well. That is cool!   Thank you so much for the tool! 

I will close the issue as I answered my own question.

**Comment by CutFlame** [comment]
I apologize that the UI wasn't clear enough. Alas, I am not a designer. Thanks for the feedback!
