### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Dyno75** [CutFlame/MCDSaveEdit#19]
Hi Mike, I sorry to bother you and it seems like a very dumb question.  But I don't know how to set everything up.  I don't know the process in order for me to use your editor.  I don't know what to do with all the PakReader and DungeonTools stuff. Are there any instructions I can find online? I already tried searching it up in my browser and YouTube.  It would be nice to know how.  If you don't want/can't help, it's fine.  Thank you in advance :)  Have a good day.

**Comment by CutFlame** [comment]
Just download the latest release (MCDSaveEdit_*.zip) from [here](https://github.com/CutFlame/MCDSaveEdit/releases/tag/release/latest), unzip it (there's just the executable in there) and then run it. It works best if you have Minecraft Dungeons installed in the default location. Thanks for being so polite!
