### ISSUE TITLE
crash on startup with v 1.2.7 and previous versions

### ISSUE THREAD

**Issue by Atlntssplayer** [CutFlame/MCDSaveEdit#20]
When I run MCDSaveEdit.exe I almost instantly get an error that "MCDSaveEdit has stopped working" and an option to either close the program or debug the program.
This is on Windows 7.
It happens with version 1.2.7 and also with previous versions. I tried them from 1.2.7 to 1.2.3 and they all behave like this.

**Comment by CutFlame** [comment]
What version of Minecraft: Dungeons do you have installed? Also, if you have the windows store version of Minecraft: Dungeons you will need to run the storepatcher.exe first.

**Comment by CutFlame** [comment]
Sorry, I don't have a windows 7 machine to test this with, so this is going to be really difficult to figure out what is wrong. MCDSaveEdit was compiled with target framework of .NET 4.7.1 so maybe try installing that? https://www.microsoft.com/en-us/download/details.aspx?id=56116
