### ISSUE TITLE
version 1.2.7 not working now..

### ISSUE THREAD

**Issue by Anthemz** [CutFlame/MCDSaveEdit#23]
Hi there, version 1.2.7 no longer working since the latest update, when will the new version release?

Thank you.
AntheMz

**Comment by thepwrtank18** [comment]
I saw 1.2.8 as a tag, but with no release :(

I assume it will be there soon

**Comment by okibcn** [comment]
It is the same issue as #22

**Comment by Aldhun** [comment]
There's now 1.2.9 but without release

**Comment by CutFlame** [comment]
I've been trying to get it published on a 3rd party website for game mods but they have some additional requirements that I'm not sure are worth the trouble. For now I have given early access to my patreon subscribers. Eventually I will publish it here on GitHub.

**Comment by Anthemz** [comment]
Hi, How to become your patron subscriber?

**Comment by CutFlame** [comment]
https://www.patreon.com/cutflame

**Comment by Anthemz** [comment]
> https://www.patreon.com/cutflame

OK, will do it tonight, thank you!
