### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by SUPERN00Bthefirst** [CutFlame/MCDSaveEdit#24]
Issue: 
Attempting to build release 1.3.0 will produce error [CS0246](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246) along with the the following warning 
```The referenced component 'Windows' could not be found```

Location: 
Constants.cs, Line 3
```using Windows.Management.Deployment;```

Request: 
Information on any packages or setup that would resolve this issue.

**Comment by CutFlame** [comment]
Try the accepted answer here:
https://stackoverflow.com/questions/54454214/how-to-access-windows-management-deployment-namespace-in-a-desktop-project-in-vs
This is only required for the windows store version though. So if you have the launcher version then you can just comment out line 3 (and then you will have to comment out lines 54-61 to get it to compile).

**Comment by codehz** [comment]
You need patch the csproj like this
```powershell
cd MCDSaveEdit\MCDSaveEdit
$orig = '..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Windows.winmd'
$real = 'C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Windows.winmd'
(Get-Content MCDSaveEdit.csproj) -Replace [regex]::escape($orig), $real | Out-File MCDSaveEdit.csproj
Get-Content MCDSaveEdit.csproj
```

**Comment by CutFlame** [comment]
I have now made that change in the code. Thank you for pointing out the problem and providing a solution!

**Comment by altinctrl** [comment]
Hey! How do I solve this?
I've been searching for hours and can't seem to find a solution.
Thanks in advance.

![image](https://user-images.githubusercontent.com/43222321/112544854-49574900-8d96-11eb-9345-100419d71915.png)

**Comment by CutFlame** [comment]
Make sure the DungeonTools submodule is up to date. That file doesn't look like that any more

**Comment by altinctrl** [comment]
Now I have these errors:
![image](https://user-images.githubusercontent.com/43222321/112555526-24b79d00-8da7-11eb-887a-f26b2836cb75.png)
