### ISSUE TITLE
Bug pak files

### ISSUE THREAD

**Issue by alexxxxstack** [CutFlame/MCDSaveEdit#28]
The program doesn't seem to work properly. There are grey icons instead of item pictures.

![image](https://user-images.githubusercontent.com/80413010/110661447-df02ae00-81c4-11eb-9a34-8c321c62ed30.png)

**Comment by alexxxxstack** [comment]
OK so finally the 1.3.0 release fixed this problem.
https://github.com/CutFlame/MCDSaveEdit/releases/tag/release%2F1.3.0

**Comment by CutFlame** [comment]
Awesome!
