### ISSUE TITLE
Microsoft Store Version Issue

### ISSUE THREAD

**Issue by greendino2000** [CutFlame/MCDSaveEdit#30]
Sorry if this is obvious but for the life of me can't find out what the "default installation location" is. So in general I can't get it to work to its fullest. Can someone please help me?

**Comment by tchia04** [comment]
Use the find in file explorer and search for "pakchunk0-WindowsNoEditor.pak" 
That is default installation location you need

**Comment by greendino2000** [comment]
Thank you very much for the help. It now is accepting it when I select the install location but it is giving me an error because of denied access. I tried running it as administrator to no avail. How do I get past this? Thanks again and sorry for the inconvenience.

**Comment by greendino2000** [comment]
Hi, I'm still having this issue. I understand you are busy, but do you know of a fix for the denied access error? Thank you.

**Comment by CutFlame** [comment]
I've never seen this error before and I have no idea why it's happening. Have you tried a different location for the .pak files? Are you able to open that file location in your file explorer? If it's still not working, could you send me a screen shot of the error?

**Comment by greendino2000** [comment]
Hi, sorry I meant to close it. I found a workaround but it's a bit complicated. As I'm using the Microsoft store version "pakchunk0-WindowsNoEditor.pak" is located in the dungeons download location inside of the windowsapps folder which is protected. This file is hidden and can not be opened even with the highest level of permissions. The file is owned by TrustedInstaller a thing in windows that overides permissions for something. I was able to find the paks by the way but I couldn't access them using the editor due to the error I mentioned. Tommorow when I'm back on pc I would be happy to post an image of the error. Basically I had to transfer ownership of a key windows folder to me which from my research usually breaks all games from the Microsoft store until you install a fresh copy of windows. So far (2 or 3 days) my games still work after transferring ownership back to TrustedInstaller. In the end giving myself ownership of the folders meant I could access the paks with your app. It does take about 2 - 4 minutes to do this whole process now that I understand it. My original plan was to duplicate the park folders every update so I wouldn't have to do this but even with every permission possible and ownerships of the files and folders it won't let me. Also things to note, the minecraft dungeons folder can be but not touched while the windowsapps folder can't even be opened, and the other thing to note is the minecraft dungeons files are literally spread between at least 3 locations (If needed I can list them)
Overall: Windows store Minecraft Dungeons paks are stored in an accessable folder which is stored in a hidden and locked folder. There is a workaround but is annoying and risky to perform and probably too complicated for a random gamer to understand. The paks can not be copied from the folder for use outside of the windowsapps folder.

Sorry that is so long. Also I would like to mention how cool and impressive your work is. If there is anything you need about the error lemme know.

**Comment by CutFlame** [comment]
Yes, this is why you need to run the storepatcher script. It extracts all those pak files out into a location you specify (which you can then provide to MCDSaveEdit).

**Comment by altinctrl** [comment]
Another option would be to use [UWPDumper](https://github.com/Wunkolo/UWPDumper).

**Comment by greendino2000** [comment]
> Yes, this is why you need to run the storepatcher script. It extracts all those pak files out into a location you specify (which you can then provide to MCDSaveEdit).

I knew I needed that for something but it wasn't clear what. How do I make it extract them to a specific location?

**Comment by altinctrl** [comment]
> > Yes, this is why you need to run the storepatcher script. It extracts all those pak files out into a location you specify (which you can then provide to MCDSaveEdit).
> 
> I knew I needed that for something but it wasn't clear what. How do I make it extract them to a specific location?

When you run the script it will open a window for you to select where to dump the files. I ran into some issues with it, so I used UWPDumper directly (the same tool the script uses). The script also modifies the game so you can run mods but you will need to run it again whenever you want to update the game.

Here is the link for [UWPDumper](https://github.com/Wunkolo/UWPDumper) if you just want the files for `MCDSaveEdit` and want to leave your game alone. To use it you just need to unzip it, open the game, open `UWPInjector.exe`, a window with a wall of green/blue text should apper, look for "Microsoft.Lovika" and type the number on the left side of it on the same window and press enter. The folder with the files should open when it finishes, but in any case they should be dumped in `C:\Users\USERNAME\AppData\Local\Packages\Microsoft.Lovika_SOMETHING\TempState\DUMP`. Note that the path is missing your user name and a random string of letters and numbers on the package name. You can move the `DUMP` folder elsewhere if you want, that's the folder you'll give to `MCDSaveEdit`.
