### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by xAhmetAbi** [CutFlame/MCDSaveEdit#33]
The images do not show for some reason.

**Comment by Jim-Zenn** [comment]
I can confirm this issue.

**Comment by Jim-Zenn** [comment]
While experimenting, I think the issue is due to the user's name contains a whitespace. Causing problems in code related to this line:

`var appDataFolderPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);`

**Comment by Jim-Zenn** [comment]
After creating a new user with a name without white space, the pak files can be found properly.

**Comment by Jim-Zenn** [comment]
To clarify, when I say "the user's name", I mean the Windows User name, which would determine the user's home directory and impact `Environment.SpecialFolder.LocalApplicationData`, causing it to contain whitespaces, too.

**Comment by avatar7652** [comment]
what do u mean kinda slow

**Comment by CutFlame** [comment]
I have recently improved this section of the code. Could you try again with MCDSaveEdit 1.3.2 (once it's published)?

**Comment by Jim-Zenn** [comment]
Sure thing

**Comment by Jim-Zenn** [comment]
It works now.

**Comment by KingKongKaram** [comment]
any way to fix this it still happens for me

**Comment by CutFlame** [comment]
It depends on which version of MCD you have.

If you have the launcher version then you need to find the folder where the .pak files are for the game. The default location is `%localappdata%\Mojang\products\dungeons\dungeons\Dungeons\Content\Paks`.

If you have the Windows Store version of MCD, you need to run https://github.com/Wunkolo/UWPDumper first and it will extract the .pak files from the game while it's running and it will ask you where you want to save them. Then when MCDSaveEdit asks where to find the game files you give the path to where you saved them.

More info in the README: https://github.com/CutFlame/MCDSaveEdit/blob/master/README.md#troubleshooting
