### ISSUE TITLE
It is always the same weapon

### ISSUE THREAD

**Issue by xAhmetAbi** [CutFlame/MCDSaveEdit#34]
Could you give more weapon types and artefacts to create from? Doing all the collecting in-game takes time

**Comment by CutFlame** [comment]
It just creates the defaults. You should be able to change it after it's created. This was a fast and easy solution to make it possible to add new items.
![TapHere](https://user-images.githubusercontent.com/6108591/111657857-72de0680-87d1-11eb-82f0-46fbb99109f0.png)
