### ISSUE TITLE
Save edit crashed upon loading file

### ISSUE THREAD

**Issue by avatar7652** [CutFlame/MCDSaveEdit#36]

**Comment by avatar7652** [comment]
in addition it says could not fine game content in given path

**Comment by CutFlame** [comment]
I recently added a How to Use section to the README: https://github.com/CutFlame/MCDSaveEdit#how-to-use if you still can't get it working, could you please send me your save file that you are trying to open and I will debug it?

**Comment by Gimdak** [comment]
i'm having the same issue with the new characters i make even if i load up characters that do work just fine and switch via recent files i see my new character's inventory briefly before the program closes 
[3E594D3A4EFE4D0A5DB5B6965B2B8AE9.zip](https://github.com/CutFlame/MCDSaveEdit/files/6214474/3E594D3A4EFE4D0A5DB5B6965B2B8AE9.zip)

**Comment by altinctrl** [comment]
Also having this issue.
The program opens normally with all images and all loaded, but as soon as I load a save file it throws an exception.
Here are two saves I used: [saves.zip](https://github.com/CutFlame/MCDSaveEdit/files/6218039/saves.zip)
And here is the call stack: [call_stack.txt](https://github.com/CutFlame/MCDSaveEdit/files/6218041/call_stack.txt)
Something about "unequipped items"
![image](https://user-images.githubusercontent.com/43222321/112767794-16f45880-8fef-11eb-8a67-7d30788ffca2.png)

**Comment by altinctrl** [comment]
> ~Also having this issue.~
> ~The program opens normally with all images and all loaded, but as soon as I load a save file it throws an exception.~
> 
> I was using `savefile.dat` instead of the `.dat` file inside of the `Characters` folder. See if that solves it for you.

Perhaps that should be added to the README to avoid further confusion.

**Comment by Zurazan** [comment]
even when opening the proper .dat file the editor just closes on me.

**Comment by Wraith1504** [comment]
same with me, i open the loader, i open my character save file and it just crashes

**Comment by CutFlame** [comment]
This will be fixed in the next release version 1.3.3. Thank you for your help!
