### ISSUE TITLE
could not decrypt pak file

### ISSUE THREAD

**Issue by Pd69bq** [CutFlame/MCDSaveEdit#37]
run into this issue on latest 1.3.0, full screenshot attached. game is launcher version running on Windows 10.

any idea how to solve this? thanks in advance

![error](https://user-images.githubusercontent.com/5948524/112443885-69800b80-8d88-11eb-91c8-4cf29340f89f.png)

**Comment by adam-lincoln** [comment]
@CutFlame Looks like Dungeons release 1.8.6.0 needs a new key. 1.8.6.0 is available through both Microsoft Store and Minecraft Launcher.

**Comment by CutFlame** [comment]
Yep. I’ve already released a new version to my patrons on Patreon and then I will release it publicly sometime later.

https://www.patreon.com/posts/49173863
