### ISSUE TITLE
Crashes upon launch ["Cannot decrypt pak files"]

### ISSUE THREAD

**Issue by NymphieDust** [CutFlame/MCDSaveEdit#38]
Likely due to the new patch, the program cannot decrypt the pak files. Attached is a picture of the error message

![image](https://user-images.githubusercontent.com/81401847/112575561-ecc05200-8dc6-11eb-957f-27261e91a0e1.png)

**Comment by Pd69bq** [comment]
same as #37

**Comment by mic369** [comment]
i'm also experiencing this problem after thinking it was an error i made, its good to see its just the update and hopefully this issue can be resolved soon

**Comment by CutFlame** [comment]
I just released the new version publicly: https://github.com/CutFlame/MCDSaveEdit/releases/tag/release%2F1.3.2

Enjoy!
