### ISSUE TITLE
Resets progress on each vendor unlock

### ISSUE THREAD

**Issue by banoodley** [CutFlame/MCDSaveEdit#4]
When I tested this earlier, saving an edit I made to increase an artifact's power level caused all of my vendor's slot progress (EG: mystery merchant's /2500 6th slot) to reset. I wondered if you knew why, is this intentional or fixable or known? Thank you!

**Comment by CutFlame** [comment]
I think I know why that is happening. I will look into it.

**Comment by CutFlame** [comment]
I have published a new version that fixes your issue. Thanks for helping me find bugs!
