### ISSUE TITLE
Suggestion: Add a copy-paste function for items

### ISSUE THREAD

**Issue by lllMohandarlll** [CutFlame/MCDSaveEdit#45]
When experimenting with objects, runes and combinations, it would be very useful to have a copy-paste function of the object, especially when you want to change only a couple of runes of the same object or when you want to use an existing one as a template multiple times.
It would save a lot of time! :)

**Comment by jimzenn** [comment]
I think a simple duplication function would go a long way. It would also be easier to implement.

**Comment by CutFlame** [comment]
This feature has been implemented in the latest version (1.3.6)!
