### ISSUE TITLE
App crashes after load a save file

### ISSUE THREAD

**Issue by louanbastos** [CutFlame/MCDSaveEdit#47]
I downloaded the latest version of the file, did everything on the tutorial, used method 2 (dump), and yet, whenever I try to load my save, the editor closes by itself.

Minecraft Dungeons: 1.8.6 (Windows Store)
MCDSaveEdit Version : 1.3.2
Used UWPDumper to get the files

**Comment by CutFlame** [comment]
Could you send me your save file that is causing the crash?

**Comment by louanbastos** [comment]
> Could you send me your save file that is causing the crash?

How can i get the save?

**Comment by louanbastos** [comment]
Here it is!
[2533275027938570.zip](https://github.com/CutFlame/MCDSaveEdit/files/6352819/2533275027938570.zip)

**Comment by CutFlame** [comment]
This will be fixed in the next release version 1.3.3. Thank you for your help!

**Comment by louanbastos** [comment]
When the new version will be released?

**Comment by KingGamerForLife** [comment]
yea for some reason it just crash on me
