### ISSUE TITLE
The Item Type shows random

### ISSUE THREAD

**Issue by zerobrine** [CutFlame/MCDSaveEdit#5]

**Comment by CutFlame** [comment]
Could you please provide some more information?
- Screenshot
- .dat file you're trying to edit
- version of the MCD you're running

**Comment by zerobrine** [comment]
![MCEDIT ERROR](https://user-images.githubusercontent.com/50146589/99305541-ec64e880-2821-11eb-8ff8-84bf16d800ab.PNG)
Lastest Version
[3A4108AA424D1B92E244BC8B5AB1D2D4.zip](https://github.com/CutFlame/MCDSaveEdit/files/5549519/3A4108AA424D1B92E244BC8B5AB1D2D4.zip)

**Comment by CutFlame** [comment]
That random box image is used when the application can't find the MCD game files in the default installed location. I just published version 1.2.4 which asks for the path to the game files which it uses to load all the content like the images and names of the items. Could you download the latest and supply the path to your game files and see if that works?
