### ISSUE TITLE
MCD win10 edition

### ISSUE THREAD

**Issue by FuveZeq** [CutFlame/MCDSaveEdit#51]
How can i find game content folder in windows?

**Comment by CutFlame** [comment]
It depends on which version of MCD you have.

If you have the launcher version then you need to find the folder where the .pak files are for the game. The default location is `%localappdata%\Mojang\products\dungeons\dungeons\Dungeons\Content\Paks`.

If you have the Windows Store version of MCD, you need to run https://github.com/Wunkolo/UWPDumper first and it will extract the .pak files from the game while it's running and it will ask you where you want to save them. Then when MCDSaveEdit asks where to find the game files you give the path to where you saved them.
