### ISSUE TITLE
Crash when opening a save file

### ISSUE THREAD

**Issue by bshep** [CutFlame/MCDSaveEdit#52]
MCD version: 1.8.6
MCDSaveEdit Version: 1.3.2

Symptoms: Crashes when loading a save file.  No error displayed.  Seems to load some of the details from the save file then window closes.

**Comment by Ducmp472** [comment]
me too, need a fix in the 1.3.3

**Comment by CutFlame** [comment]
https://github.com/CutFlame/MCDSaveEdit/releases/tag/release%2F1.3.4
Try with this new version.
