### ISSUE TITLE
Not able to launch since the Cloud Saves Update

### ISSUE THREAD

**Issue by Jaypamieukomnom** [CutFlame/MCDSaveEdit#53]
I got this following message when i try to launch the Save File Editor.

![issue](https://user-images.githubusercontent.com/83720181/117176059-c501d800-adcf-11eb-8588-928bfe4b335c.png)

**Comment by alphamite8** [comment]
Just wanted to say I am having the exact same issue after the recent update. Appreciate all your work truly.

**Comment by Zayne556** [comment]
I'm getting the same error as well

**Comment by CutFlame** [comment]
Yeah, they changed the encryption key again. Next build will work. Patreon subscribers will get early access.

**Comment by th30n31** [comment]
Where can I sign up for the patreon to get early access?

**Comment by Waffelek** [comment]
@CutFlame Hi! When will the next build be public?

**Comment by CutFlame** [comment]
https://github.com/CutFlame/MCDSaveEdit/releases/tag/release%2F1.3.4
Try with this new version.
