### ISSUE TITLE
im getting an error after selecting the pak folder

### ISSUE THREAD

**Issue by TomerGamerTV** [CutFlame/MCDSaveEdit#55]
![image](https://user-images.githubusercontent.com/44266242/117425431-736e6000-af2b-11eb-808c-875b29767201.png)

i have Minecraft dungeons from Xbox app

**Comment by TomerGamerTV** [comment]
now its just crashes after i open it

**Comment by CutFlame** [comment]
https://github.com/CutFlame/MCDSaveEdit/releases/tag/release%2F1.3.4
Try with this new version

**Comment by TomerGamerTV** [comment]
> https://github.com/CutFlame/MCDSaveEdit/releases/tag/release%2F1.3.4
> Try with this new version

tried still not working

**Comment by TomerGamerTV** [comment]
its only happaning with the windows store pak files
