### ISSUE TITLE
missing items

### ISSUE THREAD

**Issue by megaenderdragon** [CutFlame/MCDSaveEdit#56]
After opening the character file using MCD save editor no items are shown
![Zrzut ekranu (656)](https://user-images.githubusercontent.com/84520871/119003065-ba2d7280-b98d-11eb-96fe-4a4af55b5499.png)
![Zrzut ekranu (654)](https://user-images.githubusercontent.com/84520871/119003070-bac60900-b98d-11eb-9623-203ecf8aeba6.png)
![Zrzut ekranu (655)](https://user-images.githubusercontent.com/84520871/119003075-bb5e9f80-b98d-11eb-85bf-6810a32a7b32.png)

**Comment by megaenderdragon** [comment]
even with no MCD save editor associated to .dat file it doesn't work

**Comment by KingGamerForLife** [comment]
My don't even show item icons

**Comment by CutFlame** [comment]
That will have to be a feature for a future update. For now, just use the File -> Open menu option to open your character files.

**Comment by megaenderdragon** [comment]
even opening the file with open doesn't show items, nor item icons. But I found a solution for that

1. Open MCD save editor
2. Go to your characters folder
3. drag the save file on the MCD save edit window
4. It is ready! You can now edit your save
