### ISSUE TITLE
pak

### ISSUE THREAD

**Issue by nhsoot** [CutFlame/MCDSaveEdit#57]
are there any solutions for this problem?
![Screenshot_90](https://user-images.githubusercontent.com/84697131/119296603-7d11fa80-bc83-11eb-9d02-ee0239a1b842.png)

**Comment by PhoenixMC-0** [comment]
Look in the issue above this one, there is an active reply there. :D

**Comment by CutFlame** [comment]
try the latest version (1.3.6)
