### ISSUE TITLE
MCD SE not unable to launch since the Hidden Depths update

### ISSUE THREAD

**Issue by Jaypamieukomnom** [CutFlame/MCDSaveEdit#58]
![Screenshot_1](https://user-images.githubusercontent.com/83720181/119758941-a7dc9880-bea7-11eb-8476-17542c4e60d7.png)

**Comment by CutFlame** [comment]
Yeah, they changed the encryption keys again. Next release (version 1.3.5) will work. I will make sure it gets published next week sometime.

**Comment by lordgecko10** [comment]
how close is it to being done

**Comment by PhoenixMC-0** [comment]
There is a way around this, if you only need to edit item power levels and/or character level, or item rarity, then you can just switch install location. Simply uninstall, and make sure you (1) back up your character folder and (2) make sure the keep save file is turned on in the uninstall screen, then reinstall in a non-default location (I used my primary games folder) and then, when the editor fails to find MCD, simply press no game files (forget what the actual button is called) and find your character folder by going to File > Open > *your save game*. You cannot create items, change enchant slots, or anything like that, but it will work for most things.

**Comment by CutFlame** [comment]
> There is a way around this, if you only need to edit item power levels and/or character level, or item rarity, then you can just switch install location. Simply uninstall, and make sure you (1) back up your character folder and (2) make sure the keep save file is turned on in the uninstall screen, then reinstall in a non-default location (I used my primary games folder) and then, when the editor fails to find MCD, simply press no game files (forget what the actual button is called) and find your character folder by going to File > Open > _your save game_. You cannot create items, change enchant slots, or anything like that, but it will work for most things.

^ This is true ^

**Comment by megaenderdragon** [comment]
> Yeah, they changed the encryption keys again. Next release (version 1.3.5) will work. I will make sure it gets published next week sometime.

can't wait!!! Going to place some new armor properties onto my all-in-one gilded opluent armor

**Comment by megaenderdragon** [comment]
> Yeah, they changed the encryption keys again. Next release (version 1.3.5) will work. I will make sure it gets published next week sometime.

But when...

**Comment by PhoenixMC-0** [comment]
> > Yeah, they changed the encryption keys again. Next release (version 1.3.5) will work. I will make sure it gets published next week sometime.
> 
> But when...

You actually can make your Opulent Armor gilded right now by doing the method I mentioned above, as long as you have the right enchantments. If not, then you can look for an armor piece that has Luck of the Sea on it, max out that enchant, and restock merchants until the restock cost is more than 10k emeralds. This works super well, and I've gotten about ~50 uniques just from this. Seeing as you can set your player level (to get more enchant points) and set your player emerald and gold count (for restocking and buying items), with this limited version, I'd say its worth it. (side note, before this, I had never gotten a verdant robe, but with luck of the sea and high emerald count, I now have 3. So yea.)

**Comment by lordgecko10** [comment]
But when will it come out?

**Comment by PhoenixMC-0** [comment]
From what I understand, finding the key can be time consuming, but I don't really know cause *I'm not coding this*. On a side note, this program still works for the most part with this bug using the method that I mentioned, but as Cutflame said, it should be coming out this week.

**Comment by megaenderdragon** [comment]
this is the AES key, @CutFlame : 0x0A01138AC7553ECEA7E9E257B5A45FA6665679D360B270278AE5D5367B172E40

**Comment by Viinyl** [comment]
> There is a way around this, if you only need to edit item power levels and/or character level, or item rarity, then you can just switch install location. Simply uninstall, and make sure you (1) back up your character folder and (2) make sure the keep save file is turned on in the uninstall screen, then reinstall in a non-default location (I used my primary games folder) and then, when the editor fails to find MCD, simply press no game files (forget what the actual button is called) and find your character folder by going to File > Open > _your save game_. You cannot create items, change enchant slots, or anything like that, but it will work for most things.

I've tried this and It just closes when I click "OK" on the error box, tried running as admin and all the ins and outs, can't get to this "no game files" section as what I said earlier, it just closes itself after closing the error.

**Comment by PhoenixMC-0** [comment]
It did the same thing for me, however my install of MCD has been messed up for a long time because I transferred my save data (all of it) from another computer to my new one back when MCD had its own launcher. Did the error change from looking like the picture at the top of this thread to something like this?
![image](https://user-images.githubusercontent.com/84997076/120370855-5468b100-c2d2-11eb-88ae-78b76cc78e4b.png)

**Comment by Viinyl** [comment]
Yeah it looks like that, when I click "OK" it just closes the entire thing, i'm just wanting to set my gear up to the current max power level but none of my old editors are working either.

**Comment by Maksman2000** [comment]
When the program will be updated

**Comment by megaenderdragon** [comment]
> When the program will be updated

I have no Idea. He said this week

**Comment by CutFlame** [comment]
New version is released (1.3.6)
