### ISSUE TITLE
image?

### ISSUE THREAD

**Issue by Sueltan** [CutFlame/MCDSaveEdit#59]
how i fix this missing image? i use Windows 10 version Minecraft Dungeons
![Screenshot_1](https://user-images.githubusercontent.com/78491115/120097754-7e986280-c15c-11eb-9445-457d31ee4253.jpg)

**Comment by PhoenixMC-0** [comment]
Did you boot the program without selecting the game directory by pressing "no game files"? If so, that should be the reason as this happened to me when I booted it as well. Don't think that there is anything that can be done to fix this at the moment, refer to the issue listed before this one for clarification.

**Comment by Sueltan** [comment]
> Did you boot the program without selecting the game directory by pressing "no game files"? If so, that should be the reason as this happened to me when I booted it as well. Don't think that there is anything that can be done to fix this at the moment, refer to the issue listed before this one for clarification.

i boot the program with game directory but still no image

**Comment by CutFlame** [comment]
Please look at the [troubleshooting](https://github.com/CutFlame/MCDSaveEdit#troubleshooting) section of the readme.
