### ISSUE TITLE
Improved startup process: Sugestion

### ISSUE THREAD

**Issue by PhoenixMC-0** [CutFlame/MCDSaveEdit#60]
From this latest issue, I think that there may be a way around this that allows people to have their dungeons files in the same directory, but still be able to use the tool.

The Idea: On start, make the start window offer option to, (A) Boot without game files, and then select the character save in the editor window (this would negate decryption issues slightly, as right now the tool just makes you close itself if the files are in the right spot, but it can't decrypt them.), (B) Boot with game files (when the new key is found and added), or (C) Select a custom directory if your MCD is saved somewhere else that is not the default location. I don't know if this is possible, but it would allow ease of access for people and it would bypass the current problem. 

The (second) Idea: Allow for the tool to set a default directory path the first time that path is used successfully, in the form of a JSON or something, for the people who have MCD installed in a different location (so they would not have to put in the file path every time, and could instead use the "Boot with game files" option with a different file path then default). 

Again, just a suggestion, and not sure if it is 100% possible, but that's my suggestion.

**Comment by ekh0074** [comment]
My MCD files are in a different directory as mine is from the store so I used UWPDumper. I think an option to bypass game files would be good. Right now I have two dumped folders - the version before Hidden Depths and the version after. Maybe besides an option to select a different folder, the option could be also not to use the game files (this option is not available after you've specified once).

**Comment by CutFlame** [comment]
I have fixed this in the latest version (1.3.6). The next time MCD decides to change the encryption keys MCDSaveEdit will fail to load the game content but it will still allow the limited functionality.
