### ISSUE TITLE
File was not in an expected format

### ISSUE THREAD

**Issue by Master-Antonio** [CutFlame/MCDSaveEdit#7]
This software dont work.
I import my .dat but dont work.

Version : 1.5.0 Minecraft Dungeon PC Xbox Pass

**Comment by Jolt9001** [comment]
I have the same issue. In addition, the program crashes after attempting to import the .dat file again or performing any actions on the interface. It presents the error message: "Error: File was not in an expected format". This message appears, it takes between 15 to 30 seconds to crash completely.

**Comment by CutFlame** [comment]
Could you please send me a copy of your .dat file that you're trying to open? If you do that I will take a look and try to add support for it.
