### ISSUE TITLE
Can modify switch save files?

### ISSUE THREAD

**Issue by NKQ123** [CutFlame/MCDSaveEdit#77]
Can I modify my own switch save file?

**Comment by Shuray-72** [comment]
Do you even tried grabbing the save file? _"just google it up lol"_

It should be named with 32 characters and maybe with .dat extension or otherwise the switch version will always read the file as .dat and ignoring the extension.

**Comment by NKQ123** [comment]
but it shows "the file was in unexpected format"
![Uploading 16291977282826414812127815940924.jpg…]()

**Comment by NKQ123** [comment]
but it still shows "the save file is in an unexpected format"

**Comment by NKQ123** [comment]
![16291980531035571927824594292312](https://user-images.githubusercontent.com/89018312/129714969-7d32b4d3-7f75-42df-9dff-1242c8ab6014.jpg)

**Comment by Shuray-72** [comment]
![image](https://user-images.githubusercontent.com/83144010/130169753-5b73458e-c430-4da0-86d0-212eabca4d9c.jpg)

**Comment by CutFlame** [comment]
See my post here: https://github.com/CutFlame/MCDSaveEdit/issues/117
