### ISSUE TITLE
It keeps Crashing on startup

### ISSUE THREAD

**Issue by VanjiRiven** [CutFlame/MCDSaveEdit#81]
![image](https://user-images.githubusercontent.com/89756246/131272553-23c5c7ae-6d70-4385-aef8-3bfb87670c61.png)

Cant i use it on windows 7 or something?

**Comment by VanjiRiven** [comment]
> ![image](https://user-images.githubusercontent.com/89756246/131272553-23c5c7ae-6d70-4385-aef8-3bfb87670c61.png)
> 
> Cant i use it on windows 7 or something?

I also have net framework

**Comment by BurAndBY** [comment]
Did you extracted the exe, or just launched it from archive?

**Comment by CutFlame** [comment]
Is this still an issue?
