### ISSUE TITLE
Can't decryt pak files 

### ISSUE THREAD

**Issue by idkanamelol** [CutFlame/MCDSaveEdit#83]
It says it cant decrypt pak files at C:\Users\[name]\AppData\local\dungeons\dungeons\Dungeons\Content\Paks

**Comment by CutFlame** [comment]
Are you using the latest version of MCDSaveEdit? (latest release is 1.3.9.1 on GitHub and 1.4.0 on Patreon)

**Comment by SuperiorSy99** [comment]
im having the same issue and im on 1.3.9.1

**Comment by CutFlame** [comment]
I assuming this problem is fixed now that MCDSaveEdit 1.4.1 is released
