### ISSUE TITLE
I can't choose an enchantment

### ISSUE THREAD

**Issue by kyobiemon** [CutFlame/MCDSaveEdit#9]
You cannot select an enchantment.
When I try to select an enchantment, the box is empty.
No icon image.
Is there a way to fix it?

**Comment by kyobiemon** [comment]
![名称未設定-1](https://user-images.githubusercontent.com/74512436/99197887-991a7800-27d8-11eb-9bec-6c53e63f3a97.jpg)

**Comment by CutFlame** [comment]
The current implementation pulls the list of available enchantments from the game files from the default install location. It seems like it can't detect where your game is installed. I will have to add a backup list of enchantments to select from.

**Comment by kyobiemon** [comment]
Thanks for the reply.
Which is the default installation directory?
Also, does that mean I can move the data over there?

**Comment by CutFlame** [comment]
Specifically it needs access to the .pak files that the game installs. The default installation directory that it looks in is "%localappdata%\Mojang\products\dungeons\dungeons\Dungeons\Content\Paks". So, yes, if you find the .pak files from the game and copy them into that directory it should work. I suppose maybe the better long term solution is for this application to ask where the game is installed.

**Comment by kyobiemon** [comment]
It worked so well!
Thank you!
