### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by PrivateerOzz** [CutFlame/MCDSaveEdit#90]
They released a Halloween update, The launcher doesn't recognize the new items.

**Comment by InvisibleDeath** [comment]
When does the update come?

**Comment by kurnis2** [comment]
Love this editor, its INSANELY good, but it does need an update.  "does not recognize pak files"

**Comment by CutFlame** [comment]
I'm assuming this is resolved now that MCDSaveEdit 1.4.1 is released
