### ISSUE TITLE
Pak File extraction.

### ISSUE THREAD

**Issue by Acebeastyt** [CutFlame/MCDSaveEdit#97]
I own the Microsoft store version of Dungeons and I'm not too sure how to use the UWP software. Can I get some help on this or at least be given the command I need to un-pack them?

**Comment by Acebeastyt** [comment]
All I need is the information on how to access .pak files so I can use your application. I really would like an answer quickly but I know this is a busy time.

**Comment by CutFlame** [comment]
UWPDumper extracts the .pak files from the game as it is running. Basically launch the game, then launch UWPDumper and follow the prompts and it will ask where you want the pak files to be extracted to. Then, when MCDSaveEdit asks you give it that location and it should work with all the images.
