### ISSUE TITLE
Pak files not reading

### ISSUE THREAD

**Issue by FluffyTGW** [CutFlame/MCDSaveEdit#99]
i followed all the steps correctly but the files wont work. i am using version McDSaveEdit 1.4.1 and MCD version 4.22.3.0
Windows 10
I use the Xbox App to launch the game

![image](https://user-images.githubusercontent.com/96155727/146106631-65847330-b8d2-4f08-b09b-f275663615eb.png)
![image](https://user-images.githubusercontent.com/96155727/146106758-8e8c9e9a-c585-4bf0-bd58-4c317ae0bc41.png)
![image](https://user-images.githubusercontent.com/96155727/146106880-4c5f8260-29c2-4c9d-ba7d-c8bca4972a95.png)

**Comment by ExE-Boss** [comment]
The editor hasn’t yet been updated to support the new **[Cloudy Climb][MCD:Cloudy_Climb]** update.

[MCD:Cloudy_Climb]: https://minecraft.fandom.com/wiki/Minecraft_Dungeons:Cloudy_Climb

**Comment by CoderQCFromScraatch** [comment]
its updated now
